name: CD

on: push
  paths:
    # Trigger only when docs/wiki directory changes
    - 'up_enhsp/**'
    - 'setup.py'
jobs:
  deploy-test-pypi:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
  
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup java for ENHSP
      uses: actions/setup-java@v2
      with:
          distribution: 'microsoft'
          java-version: '17'
    - name: Make distrib
      run: |
        python3 -m pip install wheel
        # Create package files
        python3 setup.py sdist --format=gztar
        # Wheel file
        python3 setup.py bdist_wheel
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}